### ISSUE TITLE
Nicolai: maak een commit in sprookje.md

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/blue_monkeys#19]
* `clone` de code op je computer. Tip `git clone`
 * verander `sprookje.md`. Tip: `cd` en `notepad sprookje.md`
 * `add`, `commit`, `push`  de code

Zie [git_voor_jonge_tieners](https://github.com/richelbilderbeek/git_voor_jonge_tieners) hoe dat moet,

Voor de pro's:
 * we werken nog op `master`

**Comment by noobie981** [comment]
ik weet niet precies hoe het werkt maar (Misschien) ik probeer het. @RafayelGardishyan Sub To Him

**Comment by noobie981** [comment]
@noobie981 werkt op Master met git clone en git bash.

> Ik Raak Het Wel Soms Kwijt. (Laptop Veranderd Door Een Andere Te Pakken) <

**Comment by richelbilderbeek** [comment]
Hoi @noobie981, zou jij mijn Team Octane programmeur Rafayel met rust kunnen laten AUB? Ik heb liever dat hij programmeert dan dit soort spam mailtjes leest :+1:
