### ISSUE TITLE
Annika: log in en sluit deze Issue 

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/blue_monkeys#23]

**Comment by annikabroere** [comment]
hoi allemaal

**Comment by annikabroere** [comment]
hoi hoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihoihioihoihhiohoihoihoihioioihooihihoihoihoihohiho
\

**Comment by noobie981** [comment]
ik ga je doden
