### ISSUE TITLE
Zet de GitHub namen in de README

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/blue_monkeys#34]

**Comment by rickdecoolegast** [comment]
hoi

**Comment by annikabroere** [comment]
hoi

**Comment by rickdecoolegast** [comment]
hoi

**Comment by rickdecoolegast** [comment]
hoi

**Comment by rickdecoolegast** [comment]
hoi

**Comment by rickdecoolegast** [comment]
lol

**Comment by rickdecoolegast** [comment]
nicolay

**Comment by rickdecoolegast** [comment]
ga ook chatten

**Comment by annikabroere** [comment]
wat nou lol

**Comment by rickdecoolegast** [comment]
ik wil dat nicolay ook gaat chatten

**Comment by annikabroere** [comment]
wauw

**Comment by rickdecoolegast** [comment]
ja echt wauw

**Comment by annikabroere** [comment]
jij bent raar

**Comment by rickdecoolegast** [comment]
🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by rickdecoolegast** [comment]
hihihihihihi

**Comment by annikabroere** [comment]
yhjmu7ik87ujnh67jmynhth

**Comment by rickdecoolegast** [comment]
wat?

**Comment by rickdecoolegast** [comment]
lol

**Comment by annikabroere** [comment]
dat heb jij getypt

**Comment by rickdecoolegast** [comment]
wat schrijf je op?

**Comment by rickdecoolegast** [comment]
niet hoor😒

**Comment by rickdecoolegast** [comment]
lol!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by annikabroere** [comment]
raar kind

**Comment by annikabroere** [comment]
ik weet waar je woont

**Comment by rickdecoolegast** [comment]
niet waar

**Comment by rickdecoolegast** [comment]
waar dan?

**Comment by annikabroere** [comment]
echt wel

**Comment by rickdecoolegast** [comment]
??????

**Comment by rickdecoolegast** [comment]
klaar?

**Comment by rickdecoolegast** [comment]
klaar????????????????????????????????/

**Comment by rickdecoolegast** [comment]
k

**Comment by rickdecoolegast** [comment]
l

**Comment by rickdecoolegast** [comment]
a

**Comment by rickdecoolegast** [comment]
a

**Comment by rickdecoolegast** [comment]
r

**Comment by rickdecoolegast** [comment]
=

**Comment by rickdecoolegast** [comment]
ik bedoel ?

**Comment by rickdecoolegast** [comment]
klaasr?

**Comment by rickdecoolegast** [comment]
r?

**Comment by annikabroere** [comment]
mongolie
in de irritante kinderen wijk
nummer:  0
jouw leeftijd

**Comment by rickdecoolegast** [comment]
hahahahahahahahahahahahahahihihihihihihihihihihihihi

**Comment by rickdecoolegast** [comment]
en niet hoor

**Comment by rickdecoolegast** [comment]
lol

**Comment by annikabroere** [comment]
jemigdepemig

**Comment by rickdecoolegast** [comment]
oh mijn god

**Comment by rickdecoolegast** [comment]
what dom

**Comment by annikabroere** [comment]
kutuiyhjndjhvrvfedcnugfidhbKUHFIKUYTTKTYUHGRDHDUIPLKYUGSYUSGJKWGUHHYUU

**Comment by rickdecoolegast** [comment]
omg!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by annikabroere** [comment]
hoi

**Comment by annikabroere** [comment]
hgh

**Comment by rickdecoolegast** [comment]
doe gewoon muziek

**Comment by rickdecoolegast** [comment]
hihihihihihihihi

**Comment by rickdecoolegast** [comment]
kom op

**Comment by annikabroere** [comment]
ik had muziek op maar nu niet meer door dat irritante kind

**Comment by rickdecoolegast** [comment]
kom op nicolay

**Comment by annikabroere** [comment]
nou ik wil muziek

**Comment by annikabroere** [comment]
niet eerlijk

**Comment by noobie981** [comment]
Hoi

**Comment by annikabroere** [comment]
hoi

**Comment by noobie981** [comment]
- ga naar downloads

- klik op een profiel

- klikop opslaan ga je terug downloads dan heb je hem

-

**Comment by noobie981** [comment]
-
-
-
-
-

-
-
-
-
-

-
-
-
-
-
-

-
-
-

**Comment by annikabroere** [comment]
help gewoon

**Comment by noobie981** [comment]
ok dikkie

**Comment by noobie981** [comment]
# #35

**Comment by noobie981** [comment]
Misschien willen jullie met mij chatten of wat of gaan jullie perse DIKKEN ok sorry maar ik vind het wel leuk om te chatten en ik stuur ZOIEZO men profiel dusdat komt zoiezo goed hier is het dan @noobie981 hier en dankjewel.

**Comment by noobie981** [comment]
hoi
hoi
hoi
hoi
hoi
hoi------------------------

**Comment by annikabroere** [comment]
lol

**Comment by annikabroere** [comment]
hgh

**Comment by annikabroere** [comment]
loooooooooooooooooookjuhhhhaqwsedrftgyhujikolp;[']]]]]\zasxdcfvgbhnjmk,.;/'']/1q2w3e45r6gt7y8uji90o-p=de5rf6gty7huj

**Comment by rickdecoolegast** [comment]
echt?

**Comment by rickdecoolegast** [comment]
realy?

**Comment by noobie981** [comment]
hoi

**Comment by rickdecoolegast** [comment]
andtwoord!!!!!!!!!!!!!!!!!!1

**Comment by rickdecoolegast** [comment]
hallo nooby

**Comment by rickdecoolegast** [comment]
noobie

**Comment by noobie981** [comment]
ik ben serious aan het antwoorden sooo GA DICKEN MET JE FAMILIE

**Comment by rickdecoolegast** [comment]
wtf

**Comment by rickdecoolegast** [comment]
?????

**Comment by annikabroere** [comment]
beffennebdcetbzanxnhudyefhmssfrrcc

**Comment by rickdecoolegast** [comment]
realy??????

**Comment by rickdecoolegast** [comment]
annika

**Comment by rickdecoolegast** [comment]
GA AAN HET WERK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! NUUUUU!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by annikabroere** [comment]
ja wat is er met mijn naam

**Comment by noobie981** [comment]
Ok sorry

Diikekdu3hewbd gyvfhenbv rucnvhuer321omden hjd2cbhf ecwdnhcjvsbviugrteinovuyfwgbuierjguiergvyurehgueryeruygvsbvhsbchsdbvyug n YOU FUCKIN BITCHH uhfrtgi9vubhgt5nu4fvnf4rd3ucfvgt5j4

**Comment by rickdecoolegast** [comment]
NEE GEEN SORRY!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! AAN HET WERK!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!1 NUUUUUUUUUUUUUUUU!!!!!!!!!!!!!!

**Comment by noobie981** [comment]
ok sorry meester

**Comment by annikabroere** [comment]
azqwsxedcrfvtgbyhunjimko,l

**Comment by rickdecoolegast** [comment]
hoi ik ben online

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by rickdecoolegast** [comment]
hallo?
domie

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by annikabroere** [comment]
wat

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by rickdecoolegast** [comment]
hahahaha🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣🤣

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by noobie981** [comment]
LOL

**Comment by rickdecoolegast** [comment]
wtf

**Comment by rickdecoolegast** [comment]
NEEEEEEEEEEEEEEEEEEEEEEEEE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! PLS NO MORE LOLS

**Comment by noobie981** [comment]
LOL LOL LOL LOL LOL LOL    nfjkb  v  vr g tg tr htrhgbfbuirn BRUIN ANESS AFLEIKIEN

**Comment by noobie981** [comment]
LOLOL

**Comment by annikabroere** [comment]
lololoo0o0l0ooooooolololololoolololoololololololololloolloollolloollolloollollollollollollol

**Comment by rickdecoolegast** [comment]
MY HAT........

**Comment by rickdecoolegast** [comment]
DIT DO BOOOOOOOOM!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by rickdecoolegast** [comment]
🤢

**Comment by rickdecoolegast** [comment]
🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢🤢

**Comment by noobie981** [comment]
- [ ] @noobie981 #36 
Duplicate of #7 🤢

**Comment by rickdecoolegast** [comment]
hoe?????????

**Comment by rickdecoolegast** [comment]
wat?????

**Comment by rickdecoolegast** [comment]
nee hoor

**Comment by rickdecoolegast** [comment]
niet waar

**Comment by noobie981** [comment]
Oh My God

**Comment by richelbilderbeek** [comment]
Genoeg onzin gepraat voor nu :rainbow:
