### ISSUE TITLE
Iedereen: doe een commit in de code van de game

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/blue_monkeys#35]
Succes :+1:

**Comment by rickdecoolegast** [comment]
hoi richel ik kon niet komen want er was een afsluiting van de kinderboeken week en het duurde tot 6 uur en later dus ik kon niet komen

**Comment by rickdecoolegast** [comment]
hopelijk kan ik volgende week wel komen 😊😊😊😊😊

**Comment by richelbilderbeek** [comment]
@rickdecoolegast: geen probleem! Hopeiijk tot volgende week :+1:
