### ISSUE TITLE
Gedragsregel: wees netjes op het internet

### ISSUE THREAD

**Issue by richelbilderbeek** [djog/blue_monkeys#4]
Ik stel de volgende gedragsregel in:

> Wij gedragen ons netjes op het internet.
>
> Onze commentaren bevatten grapjes (ook slechte), maar we blijven altijd netjes op het internet

Ik wil graag dat iedereen uit het team hieronder reageert en belooft dit ook te proberen.

**Comment by rickdecoolegast** [comment]
is er iemand online?

**Comment by rickdecoolegast** [comment]
oke riechel!

**Comment by rickdecoolegast** [comment]
he richel wat zou ik kunnen doen nu ik thuis ben want ik weet het niet? 👍

**Comment by rickdecoolegast** [comment]
he richel kunnen we de naam naar chat veranderen?

**Comment by rickdecoolegast** [comment]
wat is 1+1?

**Comment by rickdecoolegast** [comment]
kan iemand mijn vragen beantwoorden?
so ja alvast bedankt 😍✔

**Comment by richelbilderbeek** [comment]
Hoi @rickdecoolegast, ik ben niet altijd online en reageer dus niet altijd heel snel :rainbow:. Leuk dat je aan de slag wilt, #6 is de Issue voor volgende week, dus die zou je kunnen doen. Veel succes!

**Comment by rickdecoolegast** [comment]
bedankt

**Comment by richelbilderbeek** [comment]
> he richel kunnen we de naam naar chat veranderen?

@rickdecoolegast: nu en uiterlijk volgende donderdag 19:15 kun je deze naam voorstellen op #5 

:+1:

**Comment by rickdecoolegast** [comment]
bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer bedankt alweer

**Comment by rickdecoolegast** [comment]
lol

**Comment by rickdecoolegast** [comment]
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol
lol

**Comment by richelbilderbeek** [comment]
Graag gedaan :+1:

**Comment by rickdecoolegast** [comment]
👍

**Comment by rickdecoolegast** [comment]
he richel ik ben ziek dus ik kan niet komen vandaag maar ik hoop genezen te zijn als ik ga les geven dus  op zaterdag 
waneer verwachten jullie mij alvast bedankt

**Comment by rickdecoolegast** [comment]
hallo

**Comment by richelbilderbeek** [comment]
Hoi Rick, beterschap! Je bent welkom tussen 12:00-17:00. Leuk!

**Comment by rickdecoolegast** [comment]
BEDANKT

**Comment by rickdecoolegast** [comment]
uh sorry bedankt

**Comment by rickdecoolegast** [comment]
he richel ik kon donder dag niet komen want mijn vader moest werken in noorwegen en het ging een beetje raar dus ik hoop dat ik volgende week wel kan komen

**Comment by richelbilderbeek** [comment]
Hoi @rickdecoolegast: kan gebeuren! Tot volgende week :+1:

**Comment by rickdecoolegast** [comment]
tot volgende week
